### PR TITLE
Drop --target-version parameter

### PR DESCRIPTION
**Pull request by ehelms**
This parameter is no longer used by the upgrade runner as it is defined internally by the scenarios.

### CODE REVIEW

**Comment by lpramuk** [comment]
Almost LGTM.

However I've found out an issue after an upgrade to 6.16 is performed:
1) Patch stream with upstream
```
# wget -O- https://github.com/theforeman/foreman_maintain/pull/911.diff | patch -N -p1 -d /usr/share/gems/gems/foreman_maintain-*
```
2) Upgrade to 6.16
```
# satellite-maintain upgrade run -y -w repositories-validate,repositories-setup,non-rh-packages
Checking for new version of satellite-maintain...
Nothing to update, can't find new version of satellite-maintain.
Running preparation steps required to run the next scenarios
...

--------------------------------------------------------------------------------
Upgrade finished.
```
3) Run upgrade once more
```
# satellite-maintain upgrade run -y -w repositories-validate,repositories-setup,non-rh-packages
Checking for new version of satellite-maintain...
Security: kernel-core-4.18.0-553.16.1.el8_10.x86_64 is an installed security update
Security: kernel-core-4.18.0-553.8.1.el8_10.x86_64 is the currently running version
Nothing to update, can't find new version of satellite-maintain.
undefined method `target_version' for nil:NilClass
```
>>> it should just say "Nothing to update....." w/o any error

File: lib/foreman_maintain/upgrade_runner.rb [hunk 1]
```diff
@@ -34,32 +34,25 @@ def clear_current_target_version
...
-      @version = version
-      scenarios_present = find_scenarios(:tags => :upgrade_scenario).any?(&matching_version_test)
-      raise "Unknown version #{version}" unless scenarios_present
-
       @scenario_cache = {}
-      self.phase = :pre_upgrade_checks
+      @phase = :pre_upgrade_checks
+      condition = { :tags => [:upgrade_scenario, phase] }
+      matching_scenarios = find_scenarios(condition)
+      @version = matching_scenarios.first.target_version
```
Comment (lpramuk) [inline lib/foreman_maintain/upgrade_runner.rb:43]: if next scenario is not installed (next maintenance is not enabled) and you run "upgrade" then it produces:
```
undefined method `target_version' for nil:NilClass
```
Is question mark missing?
```suggestion
      @version = matching_scenarios.first.target_version?
```

**Review by lpramuk — CHANGES_REQUESTED** [review]
Please fix 
```
undefined method `target_version' for nil:NilClass
``` 
when next scenario is not yet installed

File: lib/foreman_maintain/upgrade_runner.rb (hunk 1 above)
Comment (evgeni) [reply lib/foreman_maintain/upgrade_runner.rb:43]:
```suggestion
      @version = matching_scenarios.first&.target_version
```

Safe operator is `&`, but I wonder what else that might break

Comment (evgeni) [reply lib/foreman_maintain/upgrade_runner.rb:43]:
```
[root@sat-stream-qa-rhel8 ~]# foreman-maintain upgrade check
Checking for new version of satellite-maintain...
Nothing to update, can't find new version of satellite-maintain.
[root@sat-stream-qa-rhel8 ~]# foreman-maintain upgrade run
Checking for new version of satellite-maintain...
Nothing to update, can't find new version of satellite-maintain.
--------------------------------------------------------------------------------
Upgrade finished.
```

This doesn't look correct to me. I'd have expected an error "there is nothing to upgrade to" or something like that.

**Comment by ehelms** [comment]
Updated and here is the new output:

```
          Checking for new version of rubygem-foreman_maintain...
          Nothing to update, can't find new version of rubygem-foreman_maintain.

          There are no upgrades available.
          The current version of FakeyFakeFake is 3.14.
          Consider using the update command.
```

Feel free to suggest any word smithing.

File: lib/foreman_maintain/cli/upgrade_command.rb [hunk 2]
```diff
@@ -70,16 +31,30 @@ def execute
...
         disable_self_upgrade_option
 
         def execute
           ForemanMaintain.validate_downstream_packages
           ForemanMaintain.perform_self_upgrade if allow_self_upgrade?
-          upgrade_runner.run
-          upgrade_runner.save
-          exit upgrade_runner.exit_code
+
+          if upgrade_runner.available?
```
Comment (evgeni) [inline lib/foreman_maintain/cli/upgrade_command.rb:41]: Should the `check` command get the same treatment?
Otherwise you get:
```console
[root@sat ~]# foreman-maintain upgrade check
Checking for new version of satellite-maintain...
Nothing to update, can't find new version of satellite-maintain.
[root@sat ~]# echo $?
0
```

Comment (ehelms) [reply lib/foreman_maintain/cli/upgrade_command.rb]: Done. with a little re-factoring to clean up the code for re-use.

**Review by evgeni — APPROVED** [review]

File: lib/foreman_maintain/cli/upgrade_command.rb [hunk 3]
```diff
@@ -1,85 +1,72 @@
...
 
+      def try_upgrade
+        if upgrade_runner.available?
+          yield
+        else
+          instance = ForemanMaintain.detector.feature(:instance)
+          msg = <<~BANNER
+
+            There are no upgrades available.
+            The current version of #{instance.product_name} is #{instance.current_version}.
```
Comment (evgeni) [inline lib/foreman_maintain/cli/upgrade_command.rb:29]: Currently, this prints `X.Y.Z` style versions, which is not entirely correct when there is a .z release available (it tells me 3.13.0 is current, while really 3.13.1 is out). Should we only print X.Y here?

My ACK stands regardless of the outcome of this discussion.

Comment (evgeni) [reply lib/foreman_maintain/cli/upgrade_command.rb]: Discussed offline to implement that and done so to speed things up.

**Comment by lpramuk** [comment]
@ehelms I can't re-test since there are other missing changes that you have  rebased on

**Comment by lpramuk** [comment]
Now it is more broken:
```
# rpm -q satellite rubygem-foreman_maintain
satellite-6.15.3-1.el8sat.noarch
rubygem-foreman_maintain-1.7.0-1.el8sat.noarch

# dnf repolist
Updating Subscription Management repositories.
repo id                                                                                                                                                   repo name
Satellite_Engineering_Satellite_stream_Composes_Satellite_Maintenance_stream_RHEL8                                                                        Satellite Maintenance Stream RHEL8
Satellite_Engineering_Satellite_stream_Composes_Satellite_stream_RHEL8                                                                                    Satellite Stream RHEL8
rhel-8-for-x86_64-appstream-rpms                                                                                                                          Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
rhel-8-for-x86_64-baseos-rpms                                                                                                                             Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)

# satellite-maintain upgrade run -y -w repositories-validate,repositories-setup,non-rh-packages 
Checking for new version of satellite-maintain...
Nothing to update, can't find new version of satellite-maintain.

There are no upgrades available.
The current version of Satellite is 6.15.
Consider using the update command.
```
I can't upgrade at all
